version: "3.8"

services:
  web:
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - "DB_CONNECTION=host=192.168.1.58:5432 user=postgres password=root dbname=weedvibe"
    volumes:
      - ./images:/images
